services:

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketplace_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./api/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build: ./api
    container_name: api_service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: marketplace_db
      DB_USER: root
      DB_PASSWORD: root
      PORT: 3000
    depends_on:
      - db

  web:
    build: ./web
    container_name: django_web
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      API_BASE_URL: http://api:3000
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "0.0.0.0 localhost"
      EMAIL_HOST: mailhog
      EMAIL_PORT: "1025"
    depends_on:
      - api
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP (recibe los correos de Django)
      - "8025:8025"   # UI web (para ver los correos)

volumes:
  db_data: